# Generated by Django 2.1 on 2019-04-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='description',
            field=models.TextField(default='description default text'),
        ),
    ]
