# Generated by Django 2.1 on 2019-04-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='location',
            field=models.CharField(default='my location', max_length=120),
        ),
    ]
