# Generated by Django 2.1 on 2019-04-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profiles_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank=True, default='my location', max_length=120, null=True),
        ),
    ]
