# Generated by Django 2.1 on 2019-04-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190415_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='location',
        ),
    ]
